### ISSUE TITLE
mitigate inconsistencies from unknown graph-node feature support

### ISSUE THREAD

**Issue by Theodus** [edgeandnode/gateway#526]
This is a temporary measure to mitigate inconsistencies that arise from indexers serving queries with different versions of graph-node. The gateway must enforce some feature set. This followup should be to support versioned queries (GIP-24) in indexer-service and the gateway.

## TODO
- [x] merge https://github.com/graphprotocol/indexer/pull/841, release to indexers ASAP
- [x] add a config field for `min_graph_node_version`, enforce via a filter in [indexing_status.rs](https://github.com/edgeandnode/graph-gateway/blob/main/graph-gateway/src/indexers/indexing_statuses.rs).
- [x] set minimum graph-node version to `0.33.0`, but allow unknown graph-node version for now.
- [ ] transition to strict enforcement, after substantial indexer adoption of the updated indexer-service
- [ ] GIP-24
  - [ ] add indexer-service support for versioned queries
  - [ ] add the new version field to attestations, such that the gateway supports both for the transition period
  - [ ] add gateway support for the above

**Comment by Theodus** [comment]
blocked by https://github.com/graphprotocol/indexer-rs/issues/527
