### ISSUE TITLE
fix indexing status tracking

### ISSUE THREAD

**Issue by Theodus** [edgeandnode/gateway#614]
- [x] track indexing status as performance, for fast feedback
- [x] rewrite queries to optionally insert `_special_gateway_probe: _meta { block { number hash timestamp } }` then extract from the response
- [x] remove optimistic queries
- [ ] drop recently updated statuses from periodic batch requests
- [x] consider a path toward removing RPC dependencies from the gateway
