### ISSUE TITLE
New indexer discovery service based on network subgraph

### ISSUE THREAD

**Issue by LNSD** [edgeandnode/gateway#791]
The current gateway's subgraph resolution mechanism is scattered across the codebase, making code debugging and evolution very expensive. Additionally, this current implementation has some security flaws that could put the gateway in a DoS situation in a malicious indexer.

```[tasklist]
### Tasks
- [ ] https://github.com/edgeandnode/gateway/pull/706
- [ ] https://github.com/edgeandnode/gateway/pull/753
- [ ] https://github.com/edgeandnode/gateway/pull/754
- [ ] https://github.com/edgeandnode/gateway/pull/755
- [ ] https://github.com/edgeandnode/gateway/pull/756
- [ ] https://github.com/edgeandnode/gateway/pull/757
- [ ] https://github.com/edgeandnode/gateway/pull/758
- [ ] https://github.com/edgeandnode/gateway/pull/759
- [ ] https://github.com/edgeandnode/gateway/pull/760
- [ ] https://github.com/edgeandnode/gateway/pull/761
- [ ] https://github.com/edgeandnode/gateway/pull/762
- [ ] https://github.com/edgeandnode/gateway/pull/750
- [ ] https://github.com/edgeandnode/gateway/pull/763
- [ ] https://github.com/edgeandnode/gateway/pull/769
- [ ] https://github.com/edgeandnode/gateway/pull/773
- [ ] https://github.com/edgeandnode/gateway/pull/774
- [ ] https://github.com/edgeandnode/gateway/pull/779
- [ ] https://github.com/edgeandnode/gateway/pull/780
- [ ] https://github.com/edgeandnode/gateway/pull/781
- [ ] https://github.com/edgeandnode/gateway/pull/783
- [ ] https://github.com/edgeandnode/gateway/pull/785
- [ ] https://github.com/edgeandnode/gateway/pull/790
- [ ] https://github.com/edgeandnode/gateway/pull/788
- [ ] https://github.com/edgeandnode/gateway/pull/743
```

**Comment by LNSD** [comment]
As all code has been integrated, this issue can be considered resolved. It will be shipped as part of the upcoming gateway release.
