### ISSUE TITLE
Simplify receipt signer

### ISSUE THREAD

**Issue by LNSD** [edgeandnode/gateway#802]
The current implementation relies on an `eventual` to initialize and update the receipt signer's internal mapping between indexer-deployment pairs, a.k.a. indexing ID, and the largest allocation associated with this indexing.

This dependency complicates the request-handling pipeline and can be simplified by initializing the receipt pools just in time.

```[tasklist]
### Tasks
- [ ] https://github.com/edgeandnode/gateway/pull/790
- [ ] https://github.com/edgeandnode/gateway/pull/807
- [ ] https://github.com/edgeandnode/gateway/pull/814
```
