### ISSUE TITLE
Migrate to alloy

### ISSUE THREAD

**Issue by fordN** [edgeandnode/gateway#885]
```[tasklist]
### Tasks
- [ ] https://github.com/edgeandnode/toolshed/pull/268
- [ ] chore(deps): migrate the graph-gateway to alloy-rs
- [ ] chore(deps): migrate the graph-gateway exchange_rate to alloy-rs
```
